"""Password hashing helpers for RBAC authentication.

The hash format is:
`pbkdf2_sha256$<iterations>$<salt_b64>$<digest_b64>`
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import hmac
import secrets

_ALGORITHM = "pbkdf2_sha256"
_HASH_NAME = "sha256"
_DEFAULT_ITERATIONS = 390_000
_DEFAULT_SALT_BYTES = 16
_DIGEST_BYTES = 32


def _b64_encode(data: bytes) -> str:
    """Encode bytes as base64 ASCII text without introducing newlines."""
    return base64.b64encode(data).decode("ascii")


def _b64_decode(text: str) -> bytes:
    """Decode base64 ASCII text to bytes."""
    return base64.b64decode(text.encode("ascii"), validate=True)


def hash_password(
    password: str,
    *,
    iterations: int = _DEFAULT_ITERATIONS,
    salt_bytes: int = _DEFAULT_SALT_BYTES,
) -> str:
    """Hash a password using PBKDF2-HMAC-SHA256.

    Args:
        password: Plain text password to hash.
        iterations: PBKDF2 iteration count.
        salt_bytes: Random salt size in bytes.

    Returns:
        Encoded password hash string.

    Raises:
        ValueError: If the password is empty or invalid hash parameters are used.
    """
    if not password:
        raise ValueError("password must not be empty")
    if iterations <= 0:
        raise ValueError("iterations must be > 0")
    if salt_bytes <= 0:
        raise ValueError("salt_bytes must be > 0")

    salt = secrets.token_bytes(salt_bytes)
    digest = hashlib.pbkdf2_hmac(
        _HASH_NAME,
        password.encode("utf-8"),
        salt,
        iterations,
        dklen=_DIGEST_BYTES,
    )
    return f"{_ALGORITHM}${iterations}${_b64_encode(salt)}${_b64_encode(digest)}"


def verify_password(password: str, password_hash: str) -> bool:
    """Verify a password against an encoded PBKDF2 hash.

    Args:
        password: Plain text password candidate.
        password_hash: Encoded hash string generated by `hash_password`.

    Returns:
        True when the password matches, otherwise False.
    """
    if not password or not password_hash:
        return False

    parts = str(password_hash).split("$")
    if len(parts) != 4:
        return False

    algorithm, raw_iterations, raw_salt, raw_digest = parts
    if algorithm != _ALGORITHM:
        return False

    try:
        iterations = int(raw_iterations)
        salt = _b64_decode(raw_salt)
        expected = _b64_decode(raw_digest)
    except (TypeError, ValueError, binascii.Error):
        return False

    if iterations <= 0 or len(expected) != _DIGEST_BYTES:
        return False

    calculated = hashlib.pbkdf2_hmac(
        _HASH_NAME,
        password.encode("utf-8"),
        salt,
        iterations,
        dklen=len(expected),
    )
    return hmac.compare_digest(calculated, expected)
